set number
set tabstop=4

syntax enable
set background=light
colorscheme solarized

call plug#begin()

Plug 'preservim/nerdtree'
Plug 'justinmk/vim-sneak'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'

call plug#end()

let g:airline#extensions#tabline#enabled = 1
let g:airline_theme='solarized'

nnoremap <C-t> :NERDTreeToggle<CR>
